### ISSUE TITLE
Option to ignore certain buffertypes ? 

### ISSUE THREAD

**Issue by vsedov** [TheBlob42/houdini.nvim#1]
Great plugin, but sometimes when you are using a terminal like toggleterm it can get a tiny bit jarring , is it possible to disable it on certain buffers?

**Comment by TheBlob42** [comment]
Could you specify what you exactly mean by "jarring"? Would be interested if there is something which could be done better :slightly_smiling_face: 

You could simply deactivate the plugin for terminal mode in general:
```lua
require('houdini').setup {
    escape_sequences = {
        t = false
    }
}
```

If you just want to disable it for "certain" terminals you could work with a custom function here to detect when to disable it (simply return an empty string) and when to use it (return the default escape sequence):
```lua
require('houdini').setup {
    escape_sequences = {
        t = function(first, second)
            if <your condition> then
                return '' -- disabled
            end

            -- default escape sequence
            return '<BS><BS><C-\\><C-n>'
        end
    }
}
```

Does this help you in your case?

**Comment by vsedov** [comment]
Yeah! Thanks, man, I rely on this plugin way to much for my own good :P, this is a life saver, thanks. Oh wrt "jarring", it got a bit annoying when trying to move around as it would force you out of the terminal, but this little trick fixes it, which is great.

**Comment by TheBlob42** [comment]
I am glad that it works for you :slightly_smiling_face: I should probably add this little "trick" to the documentation in case others also have a similar use case

**Comment by TheBlob42** [comment]
I have added this use case to the documentation
