### ISSUE TITLE
`jk`  shoule not escape in visual mode in neovim v0.10

### ISSUE THREAD

**Issue by lost22git** [TheBlob42/houdini.nvim#10]

**Comment by TheBlob42** [comment]
If you don't like the defaults you can simply disable the escape per mode. Just set the respective  mode in the `escape_sequences` table to `false`:

```lua
require('houdini').setup {
    escape_sequences = {
        ['v'] = false,
        -- repeat for all other modes you want to disable
    }
}
```

See also the [README](https://github.com/TheBlob42/houdini.nvim?tab=readme-ov-file#escape_sequences) or the help text

**Comment by lost22git** [comment]
This problem occurred after I recently updated the new version of neovim, so I thought it was caused by the out-of-sync between the plug-in and the new version of neovim.

But now the problem seems to be solved, thanks

**Comment by TheBlob42** [comment]
With the release of Neovim `0.10.0` I merged a branch that introduces escaping for visual and operator mode as well. This was not possible before that version due to some API limitations. Therefore the defaults did change as you noticed. Sorry if that caused any confusion.
