### ISSUE TITLE
How to disable specifically blockwise visual mode?

### ISSUE THREAD

**Issue by battlelitany** [TheBlob42/houdini.nvim#11]
Hi! Sorry to trouble you. I have houdini successfully disabled for visual mode (characterwise and linewise), but I can't seem to get it to work for disabling blockwise visual mode. 

When I hold down J to select multiple lines in blockwise visual mode, it thinks I'm trying to escape. This is my current setup:

```
return {
  "TheBlob42/houdini.nvim",
  config = function()
    require("houdini").setup({
      mappings = { "jj", "JJ", "jk", "JK" },
      escape_sequences = {
        ["v"]    = false,
        ["vs"]   = false,
        ["V"]    = false,
        ["Vs"]   = false,
        ["^V"]   = false,
        ["^Vs"]  = false,
        ['no']   = false,
        ['nov']  = false,
        ['noV']  = false,
        ['no^V'] = false,
      },
    })
  end,
}
```

Apologies for any trouble!

**Comment by TheBlob42** [comment]
I guess you have entered the `^` character literally? :thinking: 
Probably copied from the examples?

This is my bad in that case as you should not enter the `^` sign but instead press `Ctrl-v` followed by the key afterwards (in this case `Ctrl-v` again). VIM depicts this control character as `^V` but it is one char instead of two. As this does not work with the Markdown documentation I split it up for better readability, but forgot that this might be confusing. Do you think a comment regarding this would be enough for others to not run into the same "trap"?

**Comment by TheBlob42** [comment]
Ok my past self was actually aware of this problem and put this comment in the README :smile: 
![image](https://github.com/TheBlob42/houdini.nvim/assets/6849129/15c277ad-4ace-4299-9e37-ad3601374db1)

**Comment by battlelitany** [comment]
> I guess you have entered the `^` character literally? 🤔 Probably copied from the examples?
> 
> This is my bad in that case as you should not enter the `^` sign but instead press `Ctrl-v` followed by the key afterwards (in this case `Ctrl-v` again). VIM depicts this control character as `^V` but it is one char instead of two. As this does not work with the Markdown documentation I split it up for better readability, but forgot that this might be confusing. Do you think a comment regarding this would be enough for others to not run into the same "trap"?

Sorry! I'm still quite new to learning nvim and I must have missed that part of the documentation. I checked houdini.lua but I still don't quite understand how I'm supposed to annotate it. Apologies for all the trouble and newbie questions.

The other thing I forgot to mention is I'm on Windows using Windows Terminal, which uses Ctrl-v for paste. I can get rid of that keybinding, but I'd rather use Ctrl-q as an alternative to enter visual block mode. How would I specify that? I have the following line below, but it must not be correct.

```
["<C-q>"] = false,
```

**Comment by battlelitany** [comment]
Thank you! I got it to work. I wanted to add that I got it to work for Ctrl-Q as well! Sorry for the silly questions.

**Comment by TheBlob42** [comment]
Happy to hear this :+1: there are no silly questions
