### ISSUE TITLE
`i_ctrl-a` does not work

### ISSUE THREAD

**Issue by joncol** [TheBlob42/houdini.nvim#3]
Hi, nice plugin!

I've noticed a problem: when trying to use `ctrl-a` in insert mode (see `:h i_ctrl-a`), it doesn't work as expected.

It *should* insert the text that you previously inserted, but instead it inserts the text that you previously inserted _with the two last characters removed_. For example:
1. Insert the text `foobar`.
2. Leave insert mode by using the `better-escape` shortcut.
3. Enter insert mode (via `o` for example).
4. Press `ctrl-a`.

Actual result: the text `foob` is inserted.
Expected result: the text `foobar` should be inserted.

**Comment by TheBlob42** [comment]
And again I learned about a feature of (N)VIM that I didn't knew before :sweat_smile: 

I checked the documentation and found the following under `:h E29`

```
5. Read-only registers ":, ". and "%
These are '%', ':' and '.'.  You can use them only with the "p", "P",
and ":put" commands and with CTRL-R.
						*quote_.* *quote.* *E29*
	".	Contains the last inserted text (the same as what is inserted
		with the insert mode commands CTRL-A and CTRL-@).  Note: this
		doesn't work with CTRL-R on the command-line. It works a bit
		differently, like inserting the text instead of putting it
		('textwidth' and other options affect what is inserted).
```

So `CTRL-A` does not simply "paste" the last inserted text but "types" them again. And this again triggers `vim.on_key()` and the escape sequence again

So for your example that means after 2. the `.` register contains the following:

`foobarjk<BS><BS>`  
(assuming `jk` is your escape sequence)

When you then press `ctrl-a` in insert mode VIM types `foobar`, then it types `jk` which triggers the plugin and types `<BS><BS>` and then it types the rest which is `<BS><BS>` again. This results in your monitored output `foob`

Now I need to figure out a way to detect this special case and prevent it :thinking: but I am confident that there is a solution

**Comment by TheBlob42** [comment]
Please check the `fix_i_ctrl_a` branch if this fixes the issue for you as well :slightly_smiling_face:  
I would like to test it a little bit more before merging it

**Comment by joncol** [comment]
@TheBlob42: Will do, thanks for the quick fix (hopefully).

**Comment by joncol** [comment]
Just tested it quickly, and at least the basic functionality seems to work fine! Nice!

**Comment by joncol** [comment]
Hi @TheBlob42: Did you find any problems with this PR, or is it ready for merging? :)

**Comment by TheBlob42** [comment]
Sorry I did not have the time recently to look any further into it, but so far did not find anything which would prevent the PR from being merged. We can still fix it afterwards if another special case comes up :)
