### ISSUE TITLE
Not working with `C-x C-n` completion

### ISSUE THREAD

**Issue by joncol** [TheBlob42/houdini.nvim#5]
Hi!

Another somewhat esoteric edge case.

When using Vim's built-in `C-x C-n` completion in insert-mode (see `:h ins-completion`) and selecting a completion, you cannot exit insert-mode via the configured key combination.

To reproduce:

1. Start up a new file with the content:
```
some convoluted word
conv
```
2. Place the cursor at the end of the file, after `conv`.
3. Press `C-x C-n`.
4. Select the completion `convoluted`.
5. Press the Houdini key combination to exit insert mode.

# Expected result
You should exit insert-mode and get back to normal-mode.

# Actual result
You don't leave insert-mode.

**Comment by TheBlob42** [comment]
Wow what a catch, I'll have a look into this :slightly_smiling_face: 

Just to be clear about the sequencing, after point `4` you do not press `Enter` to close the popup but immediately press the houdini key combination (while the popup is open) and it does not work? Because using `Enter` in between does work for me and I just want to make sure this is the same case for you as well.

**Comment by TheBlob42** [comment]
Found it :partying_face: 

There are two insert specific completion modes `ic` and `ix` (see `:help mode()`) for the builtin completion which are not covered by default and have to added to the setup validation. I have tested it already and it seems to work fine. I will prepare a PR for this soon.

The case you have described is related to the `ic` completion mode.
For `ix` just press `CTRL-X` in insert mode and then immediately try the houdini escape combination. It will not work either.

There might be some more edge cases with these other modes that I have not encountered yet :thinking: need to check those out in more details

**Comment by TheBlob42** [comment]
You can check out the `more_modes` branch which contains the fix for this specific problem and also adds more supported modes to the plugin. I still want to test it a little longer and adapt the documentation accordingly before merging the branch
